### PR TITLE
Mark _hubService as nullable

### PR DESCRIPTION
**Pull request by jamesaorson**

### CODE REVIEW

**Comment by sre-is-nathan** [comment]
So this is related to the fail open functionality. Which results in the guards not calling the hubservice when hub isn't reachable. I'd like to come up with a more resilient strategy here than marking things as nullable and hoping future devs remember why these things are nullable.

**Comment by jamesaorson** [comment]
> So this is related to the fail open functionality. Which results in the guards not calling the hubservice when hub isn't reachable. I'd like to come up with a more resilient strategy here than marking things as nullable and hoping future devs remember why these things are nullable.

Agreed, but for now, this at least notifies us in the build of where it matters. Once we mark this as nullable, it starts to point out definitions that assume it is not null. For example, the [`Guard` model](https://github.com/StanzaSystems/sdk-dotnet/blob/main/GetStanza/Models/Guard.cs)

**Comment by sre-is-nathan** [comment]
> > So this is related to the fail open functionality. Which results in the guards not calling the hubservice when hub isn't reachable. I'd like to come up with a more resilient strategy here than marking things as nullable and hoping future devs remember why these things are nullable.
> 
> 
> 
> Agreed, but for now, this at least notifies us in the build of where it matters. Once we mark this as nullable, it starts to point out definitions that assume it is not null. For example, the [`Guard` model](https://github.com/StanzaSystems/sdk-dotnet/blob/main/GetStanza/Models/Guard.cs).

This fix isn't sufficient for me to feel comfortable silencing the compiler warning. If we change this to nullable we should add checks in the hub provider to also check if the connection to hub is null or not, and throw an exception if it is. When we fail open, no code should ever be asking the hub providers to reach out to hub. So I suppose a descriptive exception message would be useful if we ever somehow cause that situation.

**Comment by sre-is-nathan** [comment]
I would also prefer to figure out an architecture that doesn't force us to put null checks in everywhere and throw exceptions if we are in the fail open state. I'd rather have some sort of dynamic architecture that can switch freely between classes that are "failing open", and doing a lot less while waiting to reach hub again, and the normal classes that actually contact hub for the rate limiting. This architecture would also be good to lay down now so that it is easier to add different failure modes later as well (ex. falling back to a local rate limiter based off of the most recent guard configs)

**Pull request closed without merging**
